name: Java C1 with Maven in LInux
on:
   push: null
   pull_request: null
jobs:
   build:
      runs-on: ${{ matrix.os }}
      strategy:
         matrix:
            java:
# test against several Java versions:
            - 8
            - 11
            os:
            - ubuntu-latest
            include:
# includes processed after exclude
            -  java: 8
               additional-maven-args: "-Pjacoco -DrepoToken=$COVERALLS_REPO_TOKEN -DpullRequest=${{ github.event.pull_request.number }} coveralls:report"
# excludes JDK 11 on macOS and Windows
      name: Build with Java ${{ matrix.java }}
      steps:
      -  uses: actions/checkout@v3
      -  name: Set up JDK ${{ matrix.java }}
         uses: actions/setup-java@v3

         with:
            java-version: ${{ matrix.java }}
            distribution: temurin
      -  name: Cache Maven packages
         uses: actions/cache@v3
         with:
            path: ~/.m2
            key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml', '**/*.yml') }}
            restore-keys: ${{ runner.os}}-m2-
      -  name: Build with Maven
         run: |
            mvn verify surefire-report:report-only site:site -DgenerateReports=false
         working-directory: Bora.Continuous
      -  name: Generate JUnit Report
         run: |
            mvn -f Continuous/pom.xml surefire-report:report-only site:site -DgenerateReports=false
         if: ${{ always() }}
      -  name: Archive JUnit Report
         uses: actions/upload-artifact@v2
         if: ${{ always() }}
         with:
            name: surefire-report-jdk-${{ matrix.java }}
            path: '**/target/site'
      -  name: run jacoco
         run: |
            mvn verify ${{ matrix.additional-maven-args }}
         working-directory: Continuous
         env:
            COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_TOKEN }}
            